//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSConnect2.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TruckingVSConnect2.Languages.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trucking VS Connect² ist und bleibt für immer eine kostenlose Software und ist mit GPLv3 lizenziert.
        ///
        /// ähnelt.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und ähnelt.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assemblerversion ähnelt.
        /// </summary>
        internal static string ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Österreich ähnelt.
        /// </summary>
        internal static string AUSTRIA {
            get {
                return ResourceManager.GetString("AUSTRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatisch anmelden ähnelt.
        /// </summary>
        internal static string AUTO_LOG_IN {
            get {
                return ResourceManager.GetString("AUTO_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchschnitt ähnelt.
        /// </summary>
        internal static string AVERAGE {
            get {
                return ResourceManager.GetString("AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rückwärts ähnelt.
        /// </summary>
        internal static string BACKWARDS {
            get {
                return ResourceManager.GetString("BACKWARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Belgien ähnelt.
        /// </summary>
        internal static string BELGIUM {
            get {
                return ResourceManager.GetString("BELGIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrerhaus ähnelt.
        /// </summary>
        internal static string CABIN {
            get {
                return ResourceManager.GetString("CABIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fracht ähnelt.
        /// </summary>
        internal static string CARGO {
            get {
                return ResourceManager.GetString("CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrwerk ähnelt.
        /// </summary>
        internal static string CHASSIS {
            get {
                return ResourceManager.GetString("CHASSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spiel beenden ähnelt.
        /// </summary>
        internal static string CLOSE_GAME {
            get {
                return ResourceManager.GetString("CLOSE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} läuft immer noch. Schließe das Spiel, bevor die wichtigen Plugins installiert werden. ähnelt.
        /// </summary>
        internal static string CLOSE_GAME_MESSAGE {
            get {
                return ResourceManager.GetString("CLOSE_GAME_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tempomat ähnelt.
        /// </summary>
        internal static string CRUISE_CONTROL {
            get {
                return ResourceManager.GetString("CRUISE_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuell ähnelt.
        /// </summary>
        internal static string CURRENT {
            get {
                return ResourceManager.GetString("CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tschechische Republik ähnelt.
        /// </summary>
        internal static string CZECH_REPUBLIC {
            get {
                return ResourceManager.GetString("CZECH_REPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lieferungszeit ähnelt.
        /// </summary>
        internal static string DEADLINE {
            get {
                return ResourceManager.GetString("DEADLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verfügbar ähnelt.
        /// </summary>
        internal static string DEADLINE_AVAILABLE {
            get {
                return ResourceManager.GetString("DEADLINE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waren liefern ähnelt.
        /// </summary>
        internal static string DELIVER_CARGO {
            get {
                return ResourceManager.GetString("DELIVER_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dänemark ähnelt.
        /// </summary>
        internal static string DENMARK {
            get {
                return ResourceManager.GetString("DENMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ziel ähnelt.
        /// </summary>
        internal static string DESTINATION {
            get {
                return ResourceManager.GetString("DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email oder Benutzername... ähnelt.
        /// </summary>
        internal static string EMAIL_USERNAME_HINT {
            get {
                return ResourceManager.GetString("EMAIL_USERNAME_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motor ähnelt.
        /// </summary>
        internal static string ENGINE {
            get {
                return ResourceManager.GetString("ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die England ähnelt.
        /// </summary>
        internal static string ENGLAND {
            get {
                return ResourceManager.GetString("ENGLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch (English) ähnelt.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausreichender Treibstoffinhalt ähnelt.
        /// </summary>
        internal static string ENOUGH_FUEL {
            get {
                return ResourceManager.GetString("ENOUGH_FUEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal error! ähnelt.
        /// </summary>
        internal static string FATAL_ERROR {
            get {
                return ResourceManager.GetString("FATAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A fatal error has occured ähnelt.
        /// </summary>
        internal static string FATAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("FATAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateiversion ähnelt.
        /// </summary>
        internal static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort vergessen? ähnelt.
        /// </summary>
        internal static string FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frankreich ähnelt.
        /// </summary>
        internal static string FRANCE {
            get {
                return ResourceManager.GetString("FRANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Treibstoff ähnelt.
        /// </summary>
        internal static string FUEL {
            get {
                return ResourceManager.GetString("FUEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbleibende Strecke ähnelt.
        /// </summary>
        internal static string FUEL_REMAINING_DISTANCE {
            get {
                return ResourceManager.GetString("FUEL_REMAINING_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zustand ähnelt.
        /// </summary>
        internal static string FUEL_STATUS {
            get {
                return ResourceManager.GetString("FUEL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spielverzeichnis nicht gefunden ähnelt.
        /// </summary>
        internal static string GAME_DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("GAME_DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Spielverzeichnis für {0} wurde nicht gefunden. Möchtest du es selber festlegen?
        ///
        ///Nein, wenn das Spiel nicht installiert worden ist.
        ///Abbrechen, wenn du es später festlegen möchtest. ähnelt.
        /// </summary>
        internal static string GAME_DIRECTORY_NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("GAME_DIRECTORY_NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutschland ähnelt.
        /// </summary>
        internal static string GERMANY {
            get {
                return ResourceManager.GetString("GERMANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungarn ähnelt.
        /// </summary>
        internal static string HUNGARY {
            get {
                return ResourceManager.GetString("HUNGARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Lieferung ähnelt.
        /// </summary>
        internal static string IDLE {
            get {
                return ResourceManager.GetString("IDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in ähnelt.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italien ähnelt.
        /// </summary>
        internal static string ITALY {
            get {
                return ResourceManager.GetString("ITALY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschränkung ähnelt.
        /// </summary>
        internal static string LIMIT {
            get {
                return ResourceManager.GetString("LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        internal static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        internal static string LOG_OUT {
            get {
                return ResourceManager.GetString("LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angemeldet als ähnelt.
        /// </summary>
        internal static string LOGGED_IN_AS {
            get {
                return ResourceManager.GetString("LOGGED_IN_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geringer Treibstoffinhalt ähnelt.
        /// </summary>
        internal static string LOW_FUEL {
            get {
                return ResourceManager.GetString("LOW_FUEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luxemburg ähnelt.
        /// </summary>
        internal static string LUXEMBOURG {
            get {
                return ResourceManager.GetString("LUXEMBOURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minuten ähnelt.
        /// </summary>
        internal static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niederlande ähnelt.
        /// </summary>
        internal static string NETHERLANDS {
            get {
                return ResourceManager.GetString("NETHERLANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Norwegen ähnelt.
        /// </summary>
        internal static string NORWAY {
            get {
                return ResourceManager.GetString("NORWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die von ähnelt.
        /// </summary>
        internal static string OF {
            get {
                return ResourceManager.GetString("OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort... ähnelt.
        /// </summary>
        internal static string PASSWORD_HINT {
            get {
                return ResourceManager.GetString("PASSWORD_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Treibstoff nachfüllen! ähnelt.
        /// </summary>
        internal static string PLEASE_REFILL_FUEL {
            get {
                return ResourceManager.GetString("PLEASE_REFILL_FUEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polen ähnelt.
        /// </summary>
        internal static string POLAND {
            get {
                return ResourceManager.GetString("POLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produktversion ähnelt.
        /// </summary>
        internal static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachtanken erforderlich ähnelt.
        /// </summary>
        internal static string REFILL_LATER {
            get {
                return ResourceManager.GetString("REFILL_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrtstrecke ähnelt.
        /// </summary>
        internal static string ROUTE {
            get {
                return ResourceManager.GetString("ROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email oder Benutzernamen speichern ähnelt.
        /// </summary>
        internal static string SAVE_EMAIL_USERNAME {
            get {
                return ResourceManager.GetString("SAVE_EMAIL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schottland ähnelt.
        /// </summary>
        internal static string SCOTLAND {
            get {
                return ResourceManager.GetString("SCOTLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache auswählen (Select language) ähnelt.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slovenien ähnelt.
        /// </summary>
        internal static string SLOVAKIA {
            get {
                return ResourceManager.GetString("SLOVAKIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string SOURCE {
            get {
                return ResourceManager.GetString("SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeit in km/h ähnelt.
        /// </summary>
        internal static string SPEED_IN_KMH {
            get {
                return ResourceManager.GetString("SPEED_IN_KMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeit in meilen/h ähnelt.
        /// </summary>
        internal static string SPEED_IN_MPH {
            get {
                return ResourceManager.GetString("SPEED_IN_MPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschwindigkeitsbegrenzung ähnelt.
        /// </summary>
        internal static string SPEED_LIMIT {
            get {
                return ResourceManager.GetString("SPEED_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst das Spiel nun starten. ähnelt.
        /// </summary>
        internal static string START_GAME_NOW {
            get {
                return ResourceManager.GetString("START_GAME_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schweden ähnelt.
        /// </summary>
        internal static string SWEDEN {
            get {
                return ResourceManager.GetString("SWEDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Längeneinheit wechseln ähnelt.
        /// </summary>
        internal static string SWITCH_LENGTH_UNIT {
            get {
                return ResourceManager.GetString("SWITCH_LENGTH_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schweiz ähnelt.
        /// </summary>
        internal static string SWITZERLAND {
            get {
                return ResourceManager.GetString("SWITZERLAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrtzeit ähnelt.
        /// </summary>
        internal static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anhänger ähnelt.
        /// </summary>
        internal static string TRAILER {
            get {
                return ResourceManager.GetString("TRAILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getriebe ähnelt.
        /// </summary>
        internal static string TRANSMISSION {
            get {
                return ResourceManager.GetString("TRANSMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trucking VS Connect² ähnelt.
        /// </summary>
        internal static string TRUCKING_VS_CONNECT_2 {
            get {
                return ResourceManager.GetString("TRUCKING_VS_CONNECT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trucking VS Anmeldung ähnelt.
        /// </summary>
        internal static string TRUCKING_VS_LOGIN {
            get {
                return ResourceManager.GetString("TRUCKING_VS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannt ähnelt.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Begrenzung ähnelt.
        /// </summary>
        internal static string UNLIMITED {
            get {
                return ResourceManager.GetString("UNLIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update verfügbar ähnelt.
        /// </summary>
        internal static string UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein neues Update für Trucking VS Connect² ist verfügbar.
        ///Version: {0}
        ///
        ///Möchtest du es wirklich installieren? ähnelt.
        /// </summary>
        internal static string UPDATE_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug ähnelt.
        /// </summary>
        internal static string VEHICLE {
            get {
                return ResourceManager.GetString("VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wales ähnelt.
        /// </summary>
        internal static string WALES {
            get {
                return ResourceManager.GetString("WALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewicht ähnelt.
        /// </summary>
        internal static string WEIGHT {
            get {
                return ResourceManager.GetString("WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Räder ähnelt.
        /// </summary>
        internal static string WHEELS {
            get {
                return ResourceManager.GetString("WHEELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ertrag ähnelt.
        /// </summary>
        internal static string YIELD {
            get {
                return ResourceManager.GetString("YIELD", resourceCulture);
            }
        }
    }
}
