//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckingVSConnect2.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_GB() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TruckingVSConnect2.Languages.en-GB", typeof(en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ABOUT_DESCRIPTION {
            get {
                return ResourceManager.GetString("ABOUT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ASSEMBLY_VERSION {
            get {
                return ResourceManager.GetString("ASSEMBLY_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember me ähnelt.
        /// </summary>
        internal static string AUTO_LOG_IN {
            get {
                return ResourceManager.GetString("AUTO_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email or username... ähnelt.
        /// </summary>
        internal static string EMAIL_USERNAME_HINT {
            get {
                return ResourceManager.GetString("EMAIL_USERNAME_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string FILE_VERSION {
            get {
                return ResourceManager.GetString("FILE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot password? ähnelt.
        /// </summary>
        internal static string FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German (Deutsch) ähnelt.
        /// </summary>
        internal static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in ähnelt.
        /// </summary>
        internal static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password... ähnelt.
        /// </summary>
        internal static string PASSWORD_HINT {
            get {
                return ResourceManager.GetString("PASSWORD_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string PRODUCT_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save email or username ähnelt.
        /// </summary>
        internal static string SAVE_EMAIL_USERNAME {
            get {
                return ResourceManager.GetString("SAVE_EMAIL_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select language ähnelt.
        /// </summary>
        internal static string SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trucking VS Connect² ähnelt.
        /// </summary>
        internal static string TRUCKING_VS_CONNECT_2 {
            get {
                return ResourceManager.GetString("TRUCKING_VS_CONNECT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trucking VS login ähnelt.
        /// </summary>
        internal static string TRUCKING_VS_LOGIN {
            get {
                return ResourceManager.GetString("TRUCKING_VS_LOGIN", resourceCulture);
            }
        }
    }
}
